services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: pdb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./db/mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10

  adminer:
    image: adminer
    container_name: padminer 
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pbackend
    restart: unless-stopped
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      DB_ENGINE: "mysql"
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      TZ: ${TZ}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./media:/app/media
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pfrontend
    restart: unless-stopped
    environment:
      VITE_API_URL: "http://localhost:8000"
      TZ: ${TZ}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  frontend: